server:
  port: 8085
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lwmmm_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: Zjh20040301
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: 192.168.66.19
    port: 6379
    database: 0
    timeout: 1800000
    password:
    jedis:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
aliyun:
  oss:
    endpoint: file.lanxige.club   # 域
    accessKeyId: xxx  # 秘钥
    accessKeySecret: xxx # 秘钥
    bucketName: lucky-nicke  # 桶名
    url: http://file.lanxige.club  # 访问地址
  vod: # 视频
    regionId: xxx
    accessKeyId: xxx
    accessKeySecret: xxx